#ifndef GLOBAL_CONSTANTS_H
#define GLOBAL_CONSTANTS_H

#define FIVE_HUNDRED_MILLION 500000000

#define MAX_PROCESS 9
#define MAXCHAR 1024
#define PAGE_TABLE_SIZE 32
#define MAIN_MEMORY_SIZE 32
//#define NUMBER_OF_RESOURCES 20

const unsigned int FIVE_HUNDRED_MS = FIVE_HUNDRED_MILLION;


#endif
